import '../assets/styles/globals.css'
import type {Metadata} from 'next'
import {AppProps} from '@/types/AppProps'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({children}: AppProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
