import '../assets/styles/globals.css'
import type {Metadata} from 'next'
import {ReactNode} from 'react'
import {geistMono, geistSans} from '@/assets/fonts/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

interface Props {
  children: ReactNode
}

export default function RootLayout({children}: Props) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  )
}
