name: Build Next.js App

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev', 'stable']

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prettier Check
        uses: rutajdash/prettier-cli-action@v1.0.2

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint Action
        uses: wearerequired/lint-action@v2.3.0

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Lecture du code source
      pull-requests: write # Autorisation pour commenter la pull request
      checks: write # Facultatif pour gérer les contrôles d'état
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm install

      - name: Run Vitest
        run: npm run test

      - name: 'Upload Coverage'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-pull-request
          path: coverage

  report-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: 'Download Coverage Artifacts'
        uses: actions/download-artifact@v4
        with:
          name: coverage-pull-request
          path: coverage
      - name: 'Report Coverage'
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-compare-path: coverage-pull-request/coverage-summary.json

  build:
    runs-on: ubuntu-latest
    needs: ['test', 'lint', 'prettier']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Cache build output
        uses: actions/cache@v3
        with:
          path: .next
          key: ${{ runner.os }}-next-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-next-build-

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build
